CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(20) UNIQUE NOT NULL,
  "age" int NOT NULL,
  "id_roles" int NOT NULL
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "video_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) UNIQUE NOT NULL,
  "url" varchar(35) UNIQUE NOT NULL
);

CREATE TABLE "course_general" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(20) UNIQUE NOT NULL,
  "description" varchar(50) UNIQUE NOT NULL,
  "id_level" int NOT NULL,
  "id_teacher" int NOT NULL,
  "id_user" int NOT NULL,
  "id_categories" int NOT NULL,
  "id_videos" int NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_roles") REFERENCES "roles" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_categories") REFERENCES "categories" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_teacher") REFERENCES "teacher" ("id");

ALTER TABLE "course_general" ADD FOREIGN KEY ("id_videos") REFERENCES "video_course" ("id");





INSERT INTO roles (name) VALUES ('Student') , ('Teacher') , ('Admi');
INSERT 0 3
entregable=# SELECT * FROM roles;
 id |  name
----+---------
  1 | Student
  2 | Teacher
  3 | Admi
(3 filas)


entregable=#

entregable=# INSERT INTO users (name,email,password,age,id_roles) VALUES
entregable-#  ('Marco' , 'Marco@gmail.com', 4578 , 30,1),
entregable-#  ('Israel' , 'Israel@gmail.com' , 6788 , 25,1),
entregable-# ('Gerson' , 'Gerson@gmail.com' , 5890 , 20 , 2),
entregable-# ('Jorge' , 'Jorge@gmail.com' , 4589 , 32 , 3);
INSERT 0 4
entregable=# SELECT * FROM users;
 id |  name  |      email       | password | age | id_roles
----+--------+------------------+----------+-----+----------
  1 | Marco  | Marco@gmail.com  | 4578     |  30 |        1
  2 | Israel | Israel@gmail.com | 6788     |  25 |        1
  3 | Gerson | Gerson@gmail.com | 5890     |  20 |        2
  4 | Jorge  | Jorge@gmail.com  | 4589     |  32 |        3
(4 filas)

entregable=# INSERT INTO categories (name) VALUES ('Full Stack') ,('Diseño UI'), ('Sofware');
INSERT 0 3
entregable=# SELECT * FROM categories;
 id |    name
----+------------
  1 | Full Stack
  2 | Diseño UI
  3 | Sofware
(3 filas)

entregable=# INSERT INTO level (name) VALUES ('Principiantes'), ('Intermedio') , ('Avanzado');
INSERT 0 3
entregable=# SELECT * FROM level;
 id |     name
----+---------------
  1 | Principiantes
  2 | Intermedio
  3 | Avanzado
(3 filas)
entregable=# INSERT INTO teacher (name) VALUES ('Brenda') , ('Ian') , ('Andres');
INSERT 0 3
entregable=# SELECT * FROM teacher;
 id |  name
----+--------
  1 | Brenda
  2 | Ian
  3 | Andres
(3 filas)

                        ^
entregable=# INSERT INTO video_course (title , url) VALUES
entregable-# ('Front End' , 'https://Front-End.com'),
entregable-# ('Html' , 'https://Html.com'),
entregable-# ('Css' , 'https://Css.com'),
entregable-# ('JavaScript' , 'https://JavaScritp.com'),
entregable-# ('Back End' , 'https://Back-End.com');
INSERT 0 5
entregable=# SELECT * FROM video_course;
 id |   title    |          url
----+------------+------------------------
  1 | Front End  | https://Front-End.com
  2 | Html       | https://Html.com
  3 | Css        | https://Css.com
  4 | JavaScript | https://JavaScritp.com
  5 | Back End   | https://Back-End.com
(5 filas)

entregable=# INSERT INTO course_general (title,description,id_level,id_teacher,id_user,id_categories,id_videos) VALUES
entregable-#  ('Front End' , 'Crea tu pagina web', 1,1,1,1,1);
INSERT 0 1
entregable=# SELECT * FROM course_general;
 id |   title   |    description     | id_level | id_teacher | id_user | id_categories | id_videos
----+-----------+--------------------+----------+------------+---------+---------------+-----------
  1 | Front End | Crea tu pagina web |        1 |          1 |       1 |             1 |         1
(1 fila)

entregable=#  INSERT INTO course_general (title,description,id_level,id_teacher,id_user,id_categories,id_videos) VALUES
entregable-# ('Css' , 'Maqueta tu Pagina' , 2,2,3,2,3),
entregable-#  ('JavaScript' , 'Crea tu pagina Web' , 3,3,2,2,4),
entregable-#  ('Back End' , 'Crea tus querys' , 3,2,1,3,5);
INSERT 0 3
entregable=# SELECT * FROM course_general;
 id |   title    |    description     | id_level | id_teacher | id_user | id_categories | id_videos
----+------------+--------------------+----------+------------+---------+---------------+-----------
  1 | Front End  | Crea tu pagina web |        1 |          1 |       1 |             1 |         1
  4 | Css        | Maqueta tu Pagina  |        2 |          2 |       3 |             2 |         3
  5 | JavaScript | Crea tu pagina Web |        3 |          3 |       2 |             2 |         4
  6 | Back End   | Crea tus querys    |        3 |          2 |       1 |             3 |         5
(4 filas)
/* General */
entregable=#  SELECT course_general.id , course_general.title, course_general.description , level.name , users.name , categories.name, video_course.title, video_course.url, teacher.name FROM course_general JOIN level ON level.id=course_general.id_level JOIN users ON users.id=course_general.id_user JOIN categories ON categories.id=course_general.id_categories JOIN video_course ON video_course.id=course_general.id_videos JOIN teacher ON teacher.id=course_general.id_teacher;
 id |   title    |    description     |     name      |  name  |    name    |   title    |          url           |  name
----+------------+--------------------+---------------+--------+------------+------------+------------------------+--------
  1 | Front End  | Crea tu pagina web | Principiantes | Marco  | Full Stack | Front End  | https://Front-End.com  | Brenda
  4 | Css        | Maqueta tu Pagina  | Intermedio    | Gerson | Diseño UI  | Css        | https://Css.com        | Ian
  5 | JavaScript | Crea tu pagina Web | Avanzado      | Israel | Diseño UI  | JavaScript | https://JavaScritp.com | Andres
  6 | Back End   | Crea tus querys    | Avanzado      | Marco  | Sofware    | Back End   | https://Back-End.com   | Ian
(4 filas)



entregable=#
